# fly.toml app configuration file generated for young-waterfall-2947 on 2023-05-22T18:53:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-waterfall-2947"
primary_region = "den"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
